### PR TITLE
made a cli interface

### PR DESCRIPTION
**Pull request by Souvikns**
I used docopt to create a cli interface. Now the username and password field will come from the cli argument.

### CODE REVIEW

**Review by ritiek — CHANGES_REQUESTED** [review]
Thanks for the PR! However, passing password on the command-line is definitely not a good idea. Most shells maintain a history of whatever commands have been executed. It would be bad if someone else could scroll up your shell history and see both your UID and password.

An alternative would be to read both UID and password via stdin (using `input()`). Perhaps we could also optionally read the UID via a command-line argument and then only ask for password via stdin. The password on the other hand should always be read via stdin.

Also, I think it would be a better idea to use [argparse](https://docs.python.org/3/library/argparse.html) instead of docopt, since argparse is a built-in library.

I could merge this PR once these points have been addressed!

**Comment by Souvikns** [comment]
ok I will fix the issues

**Comment by ritiek** [comment]
Awesome! Let me know if you need help with anything.

**Comment by Souvikns** [comment]
I have shifted to arparse and now I am taking only the username as argument and I am calling a input function to take the password as input, then passing the credential to the log.connect function to connect

**Review by ritiek — APPROVED** [review]
Looks good to me. Thank you once again!

**Pull request merged**
